apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.image.repository }}-pod
  labels:
    app: anatomy-test
    generator: helm
spec:
  containers:
    - name: main-container
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - containerPort: {{ .Values.service.port }}
      env:
        - name: WELCOME_MESSAGE
          value: "{{ .Values.customMessage }}"
